# Generated by Django 5.0.4 on 2024-04-29 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pastor",
            fields=[
                (
                    "pastor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("fellowship", models.CharField(max_length=20)),
                (
                    "ordination_status",
                    models.CharField(default="awaiting", max_length=20),
                ),
                ("image", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
