# Generated by Django 5.0.4 on 2024-05-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_pastor"),
    ]

    operations = [
        migrations.AddField(
            model_name="pastor",
            name="is_senior",
            field=models.BooleanField(default=False),
        ),
    ]
