# Generated by Django 5.0.4 on 2024-04-24 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AppointmentSlots",
            new_name="AppointmentSlot",
        ),
    ]
