# Generated by Django 5.0.4 on 2024-04-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_rename_appointmentslots_appointmentslot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointmentslot",
            old_name="end",
            new_name="end_time",
        ),
        migrations.RenameField(
            model_name="appointmentslot",
            old_name="start",
            new_name="start_time",
        ),
    ]
