# Generated by Django 5.0.4 on 2024-04-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_rename_end_appointmentslot_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentslot",
            name="status",
            field=models.TextField(default="New"),
        ),
    ]
