# Generated by Django 5.0.4 on 2024-04-25 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_appointmentslot_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookappointment",
            name="slot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointments.appointmentslot",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ApprovedAppointments",
        ),
    ]
