# Generated by Django 5.0.4 on 2024-04-25 07:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_bookappointment_slot_delete_approvedappointments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BookAppointment",
            new_name="Appointments",
        ),
    ]
