# Generated by Django 5.0.4 on 2024-04-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_rename_bookappointment_appointments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointments",
            name="approved",
        ),
    ]
