# Generated by Django 5.0.4 on 2024-05-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_remove_appointments_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentslot",
            name="status",
            field=models.CharField(default="New", max_length=20),
        ),
    ]
