# Generated by Django 5.0.4 on 2024-04-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_joineddepartment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Sermon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("speaker", models.CharField(max_length=50)),
                ("link", models.URLField()),
                ("quote", models.TextField()),
            ],
        ),
    ]
